# Site settings
title: 唱铜 View
description: "关于计算机技术、投资理财、个人成长 | 唱铜，互联网软件工程师，INFJ，价值投资爱好者，目标是财务自由"
url: "https://leovim.github.io"

# theme
remote_theme: chesterhow/tale
permalink: /:year-:month-:day/:title
paginate: 10

# Google Analytics
google_analytics: G-1437V3F3CT

# Baidu Statistic
#baidu_statistic: 6e5f92006f4eed18f39b7cb30f420d8a

# Google AdSense
google_adsense: ca-pub-2193045272262136

# cnzz statistic
#cnzz_statistic: xxxxxxxx

copyright: ""
# Author
author:
  name: 唱铜
  url: https://leovim.github.io
  email: changtong1993@gmail.com

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jekyll/tagging
  # - jekyll-sitemap
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Navigators
nav_page_names: ["about.md"]
# can be ['feeds.pub', 'xml', 'na']
nav_feed: "feeds.pub"

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]

# Tagging
# tag_page_dir:         tag
# tag_page_layout:      tag_page
# tag_permalink_style:  pretty

# tag_page_data:
#   sitemap: false

# can be ['disqus', 'gitalk']
comments_engine: gitalk

# Disqus (Set to your disqus id)
#disqus: jekyll-tale

gitalk:
  client_id: "12e9e801f496d0860121"
  client_secret: "5ec95e5a3fd4041edbc365c4e19004f636e12994"
  repo: "leovim.github.io"
  owner: "leovim"
  admin:
    - "leovim"
